feat(errorHandle): add 3 new exception handlers
CustomerNotFoundException: returns 404 NOT_FOUND status code
VersionMismatchException: returns 409 CONFLICT status code
PreconditionRequiredException: returns 428 PRECONDITION_REQUIRED status code